SYSROOT=$(shell pwd)/sysroot

# flags
QEMUFLAGS=-no-reboot -D /tmp/qemu.log -d cpu_reset,guest_errors,int,in_asm
LDFLAGS=
CFLAGS=-ffreestanding -Wall -Wextra -Wno-unused-variable -g -O0 -Iinclude

# directories
ARCHDIR=arch/i386
DRIVERDIR=drivers
BOOTDIR=/boot/
INCLUDEDIR=/usr/include
LIBDIR=/usr/lib

AR=i686-elf-ar
AS=i686-elf-as
CC=i686-elf-gcc -isystem=$(INCLUDEDIR)
