SYSROOT=$(shell pwd)/sysroot

# flags
QEMUFLAGS  = -boot d -soundhw pcspk -machine type=q35 -smp 4 -vga std
QEMUFLAGS += -drive id=disk,file=IMAGE.img,format=raw,if=none \
			 -device ahci,id=ahci \
			 -device ide-hd,drive=disk,bus=ahci.0
QEMUFLAGS += -no-reboot -D /tmp/qemu.log -d cpu_reset,guest_errors,int,in_asm
LDFLAGS    = -Wl,-Map=kernel.map -ffreestanding

CFLAGS = -ffreestanding -Wall -Wextra -Wno-unused-variable -Wno-unused-function -Wno-pointer-to-int-cast -Wno-unused
CFLAGS := $(CFLAGS) -g -O0 -Iinclude -Wshadow -nodefaultlibs -D__x86_64__

# Subsystems
ARCHDIR=arch/x86_64
DRIVERDIR=drivers
DIR_SCHED=sched
DIR_SYNC=sync
DIR_MM=mm
DIR_FS=fs
DIR_LIB=lib
ACPI_DIR=kernel/acpi
ACPICA_DIR=kernel/acpi/acpica

# sysroot related directories
BOOTDIR=/boot
INCLUDEDIR=/usr/include
LIBDIR=/usr/lib

AR=x86_64-elf-ar
AS=x86_64-elf-as
CC=x86_64-elf-gcc -isystem=$(INCLUDEDIR)
